@echo off
title Crashing...
: A
start https://google.com/a
start https://google.com/b
start https://google.com/d
start https://google.com/e
start https://google.com/f
start https://google.com/g
start https://google.com/h
start https://google.com/i
start https://google.com/j
start https://google.com/k
start https://google.com/l
start https://google.com/m
start https://google.com/n
start https://google.com/o
start https://google.com/p
start https://google.com/q
start https://google.com/r
start https://google.com/s
start https://google.com/t
start https://google.com/u
start https://google.com/v
start https://google.com/w
start https://google.com/x
start https://google.com/y
start https://google.com/z
start https://google.com/a
start https://google.com/b
start https://google.com/d
start https://google.com/e
start https://google.com/f
start https://google.com/g
start https://google.com/h
start https://google.com/i
start https://google.com/j
start https://google.com/k
start https://google.com/l
start https://google.com/m
start https://google.com/n
start https://google.com/o
start https://google.com/p
start https://google.com/q
start https://google.com/r
start https://google.com/s
start https://google.com/t
start https://google.com/u
start https://google.com/v
start https://google.com/w
start https://google.com/x
start https://google.com/y
start https://google.com/z
start https://google.com/a
start https://google.com/b
start https://google.com/d
start https://google.com/e
start https://google.com/f
start https://google.com/g
start https://google.com/h
start https://google.com/i
start https://google.com/j
start https://google.com/k
start https://google.com/l
start https://google.com/m
start https://google.com/n
start https://google.com/o
start https://google.com/p
start https://google.com/q
start https://google.com/r
start https://google.com/s
start https://google.com/t
start https://google.com/u
start https://google.com/v
start https://google.com/w
start https://google.com/x
start https://google.com/y
start https://google.com/z
start https://google.com/a
start https://google.com/b
start https://google.com/d
start https://google.com/e
start https://google.com/f
start https://google.com/g
start https://google.com/h
start https://google.com/i
start https://google.com/j
start https://google.com/k
start https://google.com/l
start https://google.com/m
start https://google.com/n
start https://google.com/o
start https://google.com/p
start https://google.com/q
start https://google.com/r
start https://google.com/s
start https://google.com/t
start https://google.com/u
start https://google.com/v
start https://google.com/w
start https://google.com/x
start https://google.com/y
start https://google.com/z
start https://google.com/a
start https://google.com/b
start https://google.com/d
start https://google.com/e
start https://google.com/f
start https://google.com/g
start https://google.com/h
start https://google.com/i
start https://google.com/j
start https://google.com/k
start https://google.com/l
start https://google.com/m
start https://google.com/n
start https://google.com/o
start https://google.com/p
start https://google.com/q
start https://google.com/r
start https://google.com/s
start https://google.com/t
start https://google.com/u
start https://google.com/v
start https://google.com/w
start https://google.com/x
start https://google.com/y
start https://google.com/z
goto A
